#ifndef IMAGINE_RPC_COMMON_DEFINITION_H
#define IMAGINE_RPC_COMMON_DEFINITION_H

namespace Imagine_Rpc
{

#define MESSAGE_HEADER_DIVIDER "\r\n"

#define INTERNAL_ZOOKEEPER_SERVICE_NAME "Internal_Service"
#define INTERNAL_ZOOKEEPER_METHOD_NAME "Internal_Processor"
#define INTERNAL_REGISTER_SERVICE_NAME INTERNAL_ZOOKEEPER_SERVICE_NAME
#define INTERNAL_REGISTER_METHOD_NAME INTERNAL_ZOOKEEPER_METHOD_NAME
#define INTERNAL_DEREGISTER_SERVICE_NAME INTERNAL_ZOOKEEPER_SERVICE_NAME
#define INTERNAL_DEREGISTER_METHOD_NAME INTERNAL_ZOOKEEPER_METHOD_NAME

#define HEARTBEAT_INTERVAL_TIME 1
#define CLIENT_HEARTBEAT_EXPIRE_TIME 12000.0
#define SERVER_HEARTBEAT_EXPIRE_TIME 12000.0

enum class Status
{
    OK,
    ERROR
};

} // namespace Imagine_Rpc

#endif