ip: 192.168.83.130
port: 9000
zookeeper_ip: 192.168.83.130
zookeeper_port: 9999
thread_num: 5
log_name: imagine_rpc_log.log
log_path: /home/imagine/MIT6824/Imagine_Rpc/log/
max_log_file_size: 104857600
async_log: false
singleton_log_mode_: false
log_title: Imagine RPC
log_with_timestamp: true