// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_import2.proto

#ifndef PROTOBUF_test_5fimport2_2eproto__INCLUDED
#define PROTOBUF_test_5fimport2_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_test_5fimport2_2eproto();
void protobuf_AssignDesc_test_5fimport2_2eproto();
void protobuf_ShutdownFile_test_5fimport2_2eproto();

class import2requestmsg;
class import2responsemsg;

// ===================================================================

class import2responsemsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:import2responsemsg) */ {
 public:
  import2responsemsg();
  virtual ~import2responsemsg();

  import2responsemsg(const import2responsemsg& from);

  inline import2responsemsg& operator=(const import2responsemsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const import2responsemsg& default_instance();

  void Swap(import2responsemsg* other);

  // implements Message ----------------------------------------------

  inline import2responsemsg* New() const { return New(NULL); }

  import2responsemsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const import2responsemsg& from);
  void MergeFrom(const import2responsemsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(import2responsemsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:import2responsemsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_test_5fimport2_2eproto();
  friend void protobuf_AssignDesc_test_5fimport2_2eproto();
  friend void protobuf_ShutdownFile_test_5fimport2_2eproto();

  void InitAsDefaultInstance();
  static import2responsemsg* default_instance_;
};
// -------------------------------------------------------------------

class import2requestmsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:import2requestmsg) */ {
 public:
  import2requestmsg();
  virtual ~import2requestmsg();

  import2requestmsg(const import2requestmsg& from);

  inline import2requestmsg& operator=(const import2requestmsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const import2requestmsg& default_instance();

  void Swap(import2requestmsg* other);

  // implements Message ----------------------------------------------

  inline import2requestmsg* New() const { return New(NULL); }

  import2requestmsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const import2requestmsg& from);
  void MergeFrom(const import2requestmsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(import2requestmsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:import2requestmsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_test_5fimport2_2eproto();
  friend void protobuf_AssignDesc_test_5fimport2_2eproto();
  friend void protobuf_ShutdownFile_test_5fimport2_2eproto();

  void InitAsDefaultInstance();
  static import2requestmsg* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// import2responsemsg

// -------------------------------------------------------------------

// import2requestmsg

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_5fimport2_2eproto__INCLUDED
