// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_import.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "test_import.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace import_package {

namespace {

const ::google::protobuf::Descriptor* response_msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  response_msg_reflection_ = NULL;
const ::google::protobuf::Descriptor* request_msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  request_msg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_test_5fimport_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_test_5fimport_2eproto() {
  protobuf_AddDesc_test_5fimport_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "test_import.proto");
  GOOGLE_CHECK(file != NULL);
  response_msg_descriptor_ = file->message_type(0);
  static const int response_msg_offsets_[1] = {
  };
  response_msg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      response_msg_descriptor_,
      response_msg::default_instance_,
      response_msg_offsets_,
      -1,
      -1,
      -1,
      sizeof(response_msg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_msg, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_msg, _is_default_instance_));
  request_msg_descriptor_ = file->message_type(1);
  static const int request_msg_offsets_[1] = {
  };
  request_msg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      request_msg_descriptor_,
      request_msg::default_instance_,
      request_msg_offsets_,
      -1,
      -1,
      -1,
      sizeof(request_msg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_msg, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_msg, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_test_5fimport_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      response_msg_descriptor_, &response_msg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      request_msg_descriptor_, &request_msg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_test_5fimport_2eproto() {
  delete response_msg::default_instance_;
  delete response_msg_reflection_;
  delete request_msg::default_instance_;
  delete request_msg_reflection_;
}

void protobuf_AddDesc_test_5fimport_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_test_5fimport_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021test_import.proto\022\016import_package\"\016\n\014r"
    "esponse_msg\"\r\n\013request_msgb\006proto3", 74);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "test_import.proto", &protobuf_RegisterTypes);
  response_msg::default_instance_ = new response_msg();
  request_msg::default_instance_ = new request_msg();
  response_msg::default_instance_->InitAsDefaultInstance();
  request_msg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_test_5fimport_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_test_5fimport_2eproto {
  StaticDescriptorInitializer_test_5fimport_2eproto() {
    protobuf_AddDesc_test_5fimport_2eproto();
  }
} static_descriptor_initializer_test_5fimport_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

response_msg::response_msg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:import_package.response_msg)
}

void response_msg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

response_msg::response_msg(const response_msg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:import_package.response_msg)
}

void response_msg::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

response_msg::~response_msg() {
  // @@protoc_insertion_point(destructor:import_package.response_msg)
  SharedDtor();
}

void response_msg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void response_msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* response_msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return response_msg_descriptor_;
}

const response_msg& response_msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_test_5fimport_2eproto();
  return *default_instance_;
}

response_msg* response_msg::default_instance_ = NULL;

response_msg* response_msg::New(::google::protobuf::Arena* arena) const {
  response_msg* n = new response_msg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void response_msg::Clear() {
// @@protoc_insertion_point(message_clear_start:import_package.response_msg)
}

bool response_msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:import_package.response_msg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:import_package.response_msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:import_package.response_msg)
  return false;
#undef DO_
}

void response_msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:import_package.response_msg)
  // @@protoc_insertion_point(serialize_end:import_package.response_msg)
}

::google::protobuf::uint8* response_msg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:import_package.response_msg)
  // @@protoc_insertion_point(serialize_to_array_end:import_package.response_msg)
  return target;
}

int response_msg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:import_package.response_msg)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void response_msg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:import_package.response_msg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const response_msg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const response_msg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:import_package.response_msg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:import_package.response_msg)
    MergeFrom(*source);
  }
}

void response_msg::MergeFrom(const response_msg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:import_package.response_msg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void response_msg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:import_package.response_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void response_msg::CopyFrom(const response_msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:import_package.response_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool response_msg::IsInitialized() const {

  return true;
}

void response_msg::Swap(response_msg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void response_msg::InternalSwap(response_msg* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata response_msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = response_msg_descriptor_;
  metadata.reflection = response_msg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// response_msg

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

request_msg::request_msg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:import_package.request_msg)
}

void request_msg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

request_msg::request_msg(const request_msg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:import_package.request_msg)
}

void request_msg::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

request_msg::~request_msg() {
  // @@protoc_insertion_point(destructor:import_package.request_msg)
  SharedDtor();
}

void request_msg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void request_msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* request_msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return request_msg_descriptor_;
}

const request_msg& request_msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_test_5fimport_2eproto();
  return *default_instance_;
}

request_msg* request_msg::default_instance_ = NULL;

request_msg* request_msg::New(::google::protobuf::Arena* arena) const {
  request_msg* n = new request_msg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void request_msg::Clear() {
// @@protoc_insertion_point(message_clear_start:import_package.request_msg)
}

bool request_msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:import_package.request_msg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:import_package.request_msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:import_package.request_msg)
  return false;
#undef DO_
}

void request_msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:import_package.request_msg)
  // @@protoc_insertion_point(serialize_end:import_package.request_msg)
}

::google::protobuf::uint8* request_msg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:import_package.request_msg)
  // @@protoc_insertion_point(serialize_to_array_end:import_package.request_msg)
  return target;
}

int request_msg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:import_package.request_msg)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void request_msg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:import_package.request_msg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const request_msg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const request_msg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:import_package.request_msg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:import_package.request_msg)
    MergeFrom(*source);
  }
}

void request_msg::MergeFrom(const request_msg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:import_package.request_msg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void request_msg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:import_package.request_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void request_msg::CopyFrom(const request_msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:import_package.request_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool request_msg::IsInitialized() const {

  return true;
}

void request_msg::Swap(request_msg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void request_msg::InternalSwap(request_msg* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata request_msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = request_msg_descriptor_;
  metadata.reflection = request_msg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// request_msg

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace import_package

// @@protoc_insertion_point(global_scope)
